### ISSUE TITLE
Parent not appearing in mehdie

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#130] opened 2023-09-20 08:05 UTC
<img width="730" alt="Screen Shot 2023-09-20 at 11 03 43" src="https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/4381316/93d3a462-29c4-45eb-bc06-cf533baf642a">
the Parent (in the Yaqut dataset) appears in its own column but does not appear in the gui.

**Comment by tomersagi** [comment] 2023-10-04 09:39
The problem is traced to the Hit model used to store a hit result. The results on the right side come from this table, and the table does not contain the type and parent information. Moreover, there is no reliable way to link the hit to a place in the place table or the relevant tables for this information: 1) place_type and 2) place_related for which one needs a place_id. 
The hits table and Hit model do not contain the place_id for the related place, only a src_id (string) which is not unique in the place table.

**Comment by tomersagi** [comment] 2023-10-04 09:43
To remedy the situation:

- [ ] replace the "authority" field in the hits table with a dataset name
- [ ] find all usage of this field in the code and make sure they survive the update
- [ ] update this field for all existing results by joining over the task id with the django_celery_results_taskresult table
- [ ] Use the authority field and the src_id field together to retrieve the related places and the type of the hit from the respective tables by modifying the model code if possible (datasets/models.py line 312) or where the hits are retrieved for the review form (datasets/views.py line 348)

**Comment by tomersagi** [comment] 2023-10-04 09:44
@sinairusinek this fix (when done) will solve #131 and #128

**Comment by tomersagi** [comment] 2023-10-05 11:07
Hit now contains a method to extract the other place, but I am pretty sure we cannot use that in order to get a runtime result for parent and type. We need to somehow incorporate these in the context transferred to the HTML page. Perhaps using the FormSet object.

**Comment by tomersagi** [comment] 2023-10-10 12:59
Type is now showing correctly. Now working on parent.

**Closed** 2023-10-10 13:30 UTC
